version: '3.9'
services:
  api:
    env_file: .env
    image: "registry.gitlab.com/trivialsec/public-api/${BUILD_ENV}:${IMAGE_TAG:-latest}"
    container_name: api
    hostname: api.trivialsec
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TRIVIALSEC_PY_LIB_VER: ${TRIVIALSEC_PY_LIB_VER}
        BUILD_ENV: ${BUILD_ENV}
        GITLAB_USER: ${GITLAB_USER}
        GITLAB_PASSWORD: ${GITLAB_PAT}
        PYTHONUNBUFFERED: 1
        PYTHONUTF8: 1
        CFLAGS: -O0
        STATICBUILD: 1
        LC_ALL: C.UTF-8
        LANG: C.UTF-8
    command: python3 -u -d -X dev run.py
    environment:
      - APP_ENV=${APP_ENV:-Dev}
      - APP_NAME=${APP_NAME}
      - LOG_LEVEL=${LOG_LEVEL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - FLASK_RUN_PORT=5081
      - TRIVIALSEC_PY_LIB_VER=${TRIVIALSEC_PY_LIB_VER}
    ports:
      - 5081:5081
    volumes:
      - ./src/app:/srv/app/app
      - ./src/routes:/srv/app/routes
      - ./src/services:/srv/app/services
    cap_drop:
      - ALL
    cap_add:
      - DAC_OVERRIDE
      - NET_BIND_SERVICE
    healthcheck:
      test: curl -f http://localhost:5081/healthcheck || exit 1
      timeout: 20s
      retries: 10
    networks:
      default:
        aliases:
          - api
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
      resources:
        limits:
          cpus: '1.00'
          memory: 1GB
        reservations:
          memory: 500M
    logging:
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    external:
      name: trivialsec
