version: '3.6'
x-defaults: &defaults
  env_file: .env
  restart: unless-stopped
  logging:
    options:
      max-size: "10m"
      max-file: "3"

services:
  api:
    <<: *defaults
    image: trivialsec/public-api
    container_name: api
    entrypoint: python3.8
    command: ["-u", "-d", "-X", "dev", "run.py"]
    build:
      context: ./
      dockerfile: docker/Dockerfile
      args:
        COMMON_VERSION: ${COMMON_VERSION}
        AWS_ACCOUNT: ${AWS_ACCOUNT}
        AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
        AWS_REGION: ${AWS_REGION}
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        PYTHONDEBUG: 1
        PYTHONUNBUFFERED: 1
        PYTHONUTF8: 1
        PYTHONDEVMODE: 1
        PYTHONCOERCECLOCALE: warn
        CFLAGS: '-O0'
        STATICBUILD: 1
        LC_ALL: C.UTF-8
        LANG: C.UTF-8
    environment:
      - CONFIG_FILE=${CONFIG_FILE}
      - FLASK_RUN_PORT=8080
      - FLASK_DEBUG=1
      - FLASK_ENV=development
    ports:
      - 8080:8080
      - 8000:8000
    volumes:
      - ./src/app:/srv/app/app
      - ./src/routes:/srv/app/routes
      - ./src/run.py:/srv/app/run.py
    external_links:
      - mysql
      - sockets
      - redis
    cap_drop:
      - ALL
    cap_add:
      - DAC_OVERRIDE
      - NET_BIND_SERVICE
    networks:
      trivialsec:
        aliases:
          - api
    healthcheck:
      test: curl -f http://localhost:8080 || exit 1
      timeout: 20s
      retries: 10

networks:
  trivialsec:
    external: true
    name: containers-common_trivialsec
